Repository sahil-sagwekar2652/GitHub-Automation-scripts, pull requests merged in 2023-07, with the labels that each got.

#121 Add PR Template
  .github/pull_request_template.md
Labels: gssoc23, level2

#123 Added auto-comment.yml file
  .github/dependabot.yml
  .github/workflows/auto-comment.yml
Labels: gssoc23, level3

#126 Script for fork_clone.py
  scripts/fork_clone.py
Labels: gssoc23, level3

#129 Update Contributing.md file
  CONTRIBUTING.md
Labels: gssoc23, level1

#90 Create create_build.sh
  scripts/Maven build script/README.md
  scripts/Maven build script/maven_build.sh
Labels: gssoc23, level3
