Repository sahil-sagwekar2652/GitHub-Automation-scripts, pull requests merged in 2023-05, with the labels that each got.

#28 Add script to create a new GitHub repository
  scripts/create_repo.sh
Labels: gssoc23, level3

#33 Update README.md
  README.md
Labels: gssoc23, level1

#18 Add Installation Script For The Project
  .setup/install.sh
  README.md
Labels: gssoc23, level2

#39 scripts: introduce a bash script to call python script
  scripts/create_repo
  scripts/create_repo.py
Labels: gssoc23, level1

#52 added contributor graph
  README.md
Labels: gssoc23, level1

#57 Delete Repo
  scripts/delete_repo.sh
Labels: gssoc23, level3

#72 Created Website for GitHub-Automation-scripts #48
  css/style.css
  graphics/back.jpg
  graphics/repo.jpg
  index.html
  js/scripts.js
Labels: gssoc23, level3
