Repository sahil-sagwekar2652/GitHub-Automation-scripts, pull requests merged in 2023-06, with the labels that each got.

#69 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc23, level1

#82 Fix Text in README
  README.md
Labels: gssoc23, level1

#89 Added CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
Labels: gssoc23, level1

#93 Fix Text in README
  README.md
Labels: gssoc23, level1

#96 Added Documentation for create_repo.py
  scripts/create_repo.py
Labels: gssoc23, level2

#55 Added push_repo python script
  scripts/push_repo.py
Labels: gssoc23, level3

#120 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: gssoc23, level2
